import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { imagePackages, imageVersions, parseVersion } from './release-config.mjs';

export const releaseMatrixPath = 'docs/operators/release-matrix.md';

// Read the planned changes as well as disk so documentation is prepared before mutation.
export function releaseInventory(root, { changes = new Map(), versions, platformVersion } = {}) {
  const read = path => JSON.parse(changes.get(path) ?? readFileSync(resolve(root, path), 'utf8'));
  const manifest = read('package.json'), lock = read('package-lock.json');
  if (manifest.name !== 'mingd') throw new Error('Run from the mingd repository root.');
  if (lock.version !== manifest.version || lock.packages['']?.version !== manifest.version) throw new Error('Lockfile version differs for package.json.');
  parseVersion(platformVersion ?? manifest.version);
  const packages = {}, names = {};
  for (const base of ['apps', 'packages', 'services']) {
    for (const entry of readdirSync(resolve(root, base), { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      const key = `${base}/${entry.name}`;
      if (!entry.isDirectory() || !existsSync(resolve(root, key, 'package.json'))) continue;
      const data = read(`${key}/package.json`);
      parseVersion(data.version);
      if (lock.packages[key]?.version !== data.version) throw new Error(`Lockfile version differs for ${key}/package.json.`);
      const name = data.name ?? key;
      if (Object.hasOwn(packages, name)) throw new Error(`Duplicate workspace package name: ${name}.`);
      packages[name] = data.version;
      names[key] = name;
    }
  }
  const images = Object.fromEntries(Object.entries(versions ?? imageVersions(root)).map(([service, version]) => {
    const packageName = names[imagePackages[service]];
    if (!packageName) throw new Error(`Missing package for ${service}.`);
    return [service, { tag: `v${version}`, package: packageName }];
  }));
  return { schemaVersion: 1, platformVersion: platformVersion ?? manifest.version, packages, images };
}

const cell = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('|', '&#124;').replaceAll('\n', ' ');
function tables(snapshot) {
  return [
    '| Image | Image tag | Owning package | Package version in checkout |',
    '| --- | --- | --- | --- |',
    ...Object.entries(snapshot.images).map(([image, data]) => `| ${cell(image)} | ${cell(data.tag)} | ${cell(data.package)} | ${cell(snapshot.packages[data.package])} |`),
    '', '| Workspace package | Version |', '| --- | --- |',
    ...Object.entries(snapshot.packages).map(([name, version]) => `| ${cell(name)} | ${cell(version)} |`),
  ].join('\n');
}

export function renderReleaseMatrix(root, current, { extraSnapshots = [] } = {}) {
  for (const parent of ['docs', 'docs/operators']) {
    const path = resolve(root, parent);
    if (existsSync(path) && !statSync(path).isDirectory()) throw new Error('Release matrix parent is not a directory.');
  }
  const output = resolve(root, releaseMatrixPath);
  if (existsSync(output) && statSync(output).isDirectory()) throw new Error('Release matrix output is a directory.');
  const directory = resolve(root, 'releases');
  const snapshots = existsSync(directory) ? readdirSync(directory).filter(name => /^v\d+\.\d+\.\d+\.json$/.test(name)).map(name => {
    const snapshot = JSON.parse(readFileSync(resolve(directory, name), 'utf8'));
    if (snapshot.schemaVersion !== 1 || `v${snapshot.platformVersion}.json` !== name) throw new Error(`Invalid release snapshot: ${name}.`);
    return snapshot;
  }) : [];
  snapshots.push(...extraSnapshots);
  for (const snapshot of snapshots) {
    parseVersion(snapshot.platformVersion);
    for (const version of Object.values(snapshot.packages)) parseVersion(version);
    for (const image of Object.values(snapshot.images)) {
      if (!/^v\d+\.\d+\.\d+$/.test(image.tag) || !Object.hasOwn(snapshot.packages, image.package)) throw new Error('Invalid image mapping in a release snapshot.');
    }
  }
  snapshots.sort((a, b) => {
    const left = parseVersion(a.platformVersion), right = parseVersion(b.platformVersion);
    return right[0] - left[0] || right[1] - left[1] || right[2] - left[2];
  });
  return `---
title: "Platform release matrix"
editUrl: https://github.com/sxmxc/mingd/edit/main/docs/operators/release-matrix.md
---

# Platform release matrix

<!-- Generated by npm run release. Update versions through release commands; do not edit these tables. -->

This page records prepared package and image versions. It does not confirm registry
publication, deployment, or native template acceptance. Follow [deployment](deployment.md#platform-releases)
for release preparation. For supported export targets and Godot releases, see
[platforms and features](../users/build-profiles.md#supported-matrix).

## Current prepared versions

Platform version in the checkout: **v${current.platformVersion}**. Component bumps
refresh these tables without changing past platform snapshots.

Package versions describe source in the checkout. An unchanged image may have been
built with an older package version, especially when multiple images share the
builder package. Worker details and the Administration footer report the versions
actually shipped in running processes. Image digests belong in deployment records.

${tables(current)}

## Platform release history

Each platform release captures the prepared component set at that time. Its
tables remain unchanged when subsequent components advance. Optional images
are included in the inventory even when an instance does not deploy them.

${snapshots.length ? snapshots.map(snapshot => `### v${snapshot.platformVersion}\n\n[Release snapshot](../../releases/v${snapshot.platformVersion}.json)\n\n${tables(snapshot)}`).join('\n\n') : 'No platform release snapshots have been captured yet.'}
`;
}

export function writeReleaseMatrix(root, content) {
  const path = resolve(root, releaseMatrixPath);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}
